# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artDataApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('loveName', models.CharField(max_length=20)),
                ('gender', models.BooleanField(default=True)),
                ('age', models.IntegerField(null=True)),
                ('userPic', models.CharField(max_length=128, null=True)),
                ('area', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artDataApp.ArtData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogUserApp.User')),
            ],
        ),
    ]
