# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-13 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=30)),
                ('compy', models.CharField(max_length=15)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
