# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='visitLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name=b'\xe8\xae\xbf\xe9\x97\xaeIP')),
                ('area', models.CharField(max_length=30, verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe5\x9c\xb0\xe5\x9f\x9f')),
                ('compy', models.CharField(max_length=15, verbose_name=b'\xe8\xbf\x90\xe8\x90\xa5\xe5\x95\x86')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe6\x97\xb6\xe9\x97\xb4')),
            ],
        ),
    ]
