# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogUserApp', '0001_initial'),
        ('artDataApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonTreateTime', models.DateTimeField(auto_now_add=True)),
                ('tonArea', models.CharField(max_length=4000)),
                ('tonGoodTip', models.IntegerField()),
                ('tonIsDelete', models.BooleanField(default=False)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artDataApp.ArtData')),
                ('tonMesage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogUserApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_ton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tonApp.Ton')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogUserApp.User')),
            ],
        ),
    ]
