# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogUserApp', '0002_usergood'),
        ('tonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_ton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tonApp.Ton')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogUserApp.User')),
            ],
        ),
    ]
