# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artDivide', models.IntegerField()),
                ('artTitle', models.CharField(max_length=20)),
                ('artFTitle', models.CharField(max_length=50)),
                ('art', tinymce.models.HTMLField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('lookTip', models.IntegerField(default=0)),
                ('sayTip', models.IntegerField(default=0)),
                ('goodTip', models.IntegerField(default=0)),
                ('isDelete', models.BooleanField(default=False)),
                ('artPic', models.ImageField(upload_to=b'./')),
            ],
        ),
    ]
